import 'app_strings.dart';

class AppFormListData {
  AppFormListData._privateConstructor();
  static final AppFormListData _instance =
      AppFormListData._privateConstructor();
  static AppFormListData get instance => _instance;

  List<String> heightList = [
    "Below 4ft 6in",
    "4ft 6in",
    "4ft 7in",
    "4ft 8in",
    "4ft 9in",
    "4ft 10in",
    "4ft 11in",
    "4ft 12in",
    "5ft",
    "5ft 1in",
    "5ft 2in",
    "5ft 3in",
    "5ft 4in",
    "5ft 5in",
    "5ft 6in",
    "5ft 7in",
    "5ft 8in",
    "5ft 9in",
    "5ft 10in",
    "5ft 11in",
    "6ft",
    "6ft 1in",
    "6ft 2in",
    "Above 6ft 2in"
  ];

  List<String> maritalStateList = [
    "Never Married",
    "Divorced",
    "Separated",
    "Widowed",
  ];

  List<String> motherTongueList = [
    "Hindi / Urdu",
    "Angika",
    "Arabic",
    "Arunachali",
    "Assamese",
    "Awadhi",
    "Badaga",
    "Bengali",
    "Bbhojpuri",
    "Bihari",
    "brij",
    "Chatisgarhi",
    "Coorgi",
    "Dogri",
    "English",
    "French",
    "Garhwali",
    "Garo",
    "Gujrati",
    "Haryanvi",
    "Hiimachli",
    "Himachali/Pahari",
    "Kanauji",
    "Kannada",
    "Kashmiri",
    "Khandesi",
    "Khasi",
    "Konkani",
    "Koshali",
    "Kumaoni",
    "Kutchi",
    "Ladacki",
    "Lepcha",
    "Magahi",
    "Maithili",
    "Malay",
    "Malayalam",
    "Manipuri",
    "Marathi",
    "Marwari",
    "Miji",
    "Miza",
    "Monpa",
    "Nepali",
    "Punjabi",
    "Rajasthani",
    "Russian",
    "Sanskrit",
    "Santhali",
    "Sindhi",
    "Spanish",
    "Tamil",
    "Telugu",
    "Tripuri",
    "Tulu"
  ];

  List<String> sectList = ["Sunni", "Shia"];
  List<String> casteList = [
    "Aarab",
    "Aarzal",
    "Aayanavar",
    "Ansari",
    "Bagban or Baghban",
    "Barbhuiya",
    "Beigh",
    "Bhat",
    "Chhipa",
    "Dar",
    "Deccanis or Deccani",
    "Gada/Gour",
    "Gaddi",
    "Ganai",
    "Idrisi",
    "Kalal (Iraqi)",
    "Khan or Pathan",
    "Patel",
    "Pinjara",
    "Qazi",
    "Saifi",
    "Salmani",
    "Shah",
    "Tyagi",
    "TyagiVohra",
    "Wani",
    "No Caste",
    "Other",
  ];

  List<String> maslakList = [
    "Ahle Hadees",
    "Barelvi",
    "Deobandi",
    "Sufi",
    "Tablighi Jamaat",
    "Others",
  ];

  List<String> employedIdList = [
    "Business/Self Employed",
    "Civil Services",
    "Defence",
    "Government/Public Sector",
    "Private Sector",
    "Not Working"
  ];

  List<String> occupationList = [
    "Administration${AppStrings.split}Admin Professional",
    "Administration${AppStrings.split}Clerk",
    "Administration${AppStrings.split}Operator/Technician",
    "Administration${AppStrings.split}Secretary/Front Office",
    "Administration${AppStrings.split}Advertising Professional",
    "Administration${AppStrings.split}Film/Entertainment Professional",
    "Administration${AppStrings.split}Media Professional",
    "Administration${AppStrings.split}Pr Professional",
    "Agriculture${AppStrings.split}AgricultureProfessional",
    "Agriculture${AppStrings.split}Farming",
    "Airline & Aviation${AppStrings.split}Airline Professional",
    "Airline & Aviation${AppStrings.split}Flight Attendant",
    "Airline & Aviation${AppStrings.split}Pilot",
    "Architecture${AppStrings.split}Architect",
    "Architecture${AppStrings.split}Chartered Accountant",
    "BPO & Customer Service${AppStrings.split}BPO/ITes Professional",
    "BPO & Customer Service${AppStrings.split}Customer Service",
    "Corporate Management Professionals${AppStrings.split}Analyst",
    "Corporate Management Professionals${AppStrings.split}Consultant",
    "Corporate Management Professionals${AppStrings.split}Corporate Communication",
    "Corporate Management Professionals${AppStrings.split}Corporate Planning",
    "Corporate Management Professionals${AppStrings.split}HR Professional",
    "Corporate Management Professionals${AppStrings.split}Marketing Professional",
    "Corporate Management Professionals${AppStrings.split}Operation management",
    "Corporate Management Professionals${AppStrings.split}Product manager",
    "Corporate Management Professionals${AppStrings.split}Program Manager",
    "Corporate Management Professionals${AppStrings.split}Project Manager - Non IT",
    "Corporate Management Professionals${AppStrings.split}Sales Professional",
    "Doctor${AppStrings.split}Dentist",
    "Doctor${AppStrings.split}Doctor",
    "Doctor${AppStrings.split}Surgeon",
    "Education & Training${AppStrings.split}Education Professional",
    "Education & Training${AppStrings.split}Education Institution Owner",
    "Education & Training${AppStrings.split}Librarian",
    "Education & Training${AppStrings.split}Professor/Lecturer",
    "Education & Training${AppStrings.split}Research Assistant",
    "Education & Training${AppStrings.split}Teacher",
    "Engineering${AppStrings.split}Electronics Engineer",
    "Engineering${AppStrings.split}Engineer",
    "Engineering${AppStrings.split}Hardware/Telecom Engineer",
    "Engineering${AppStrings.split}Non - IT Engineer",
    "Engineering${AppStrings.split}Quality Assurance Engineer",
    "Science & Research${AppStrings.split}Reseach Professional",
    "Science & Research${AppStrings.split}Science Professional",
    "Science & Research${AppStrings.split}Scientist",
    "Software & IT${AppStrings.split}Animator",
    "Software & IT${AppStrings.split}Cyber/Network Security",
    "Software & IT${AppStrings.split}Project Manager - IT",
    "Software & IT${AppStrings.split}Project Lead - IT",
    "Software & IT${AppStrings.split}Quality Assurance Engineer - IT",
    "Software & IT${AppStrings.split}Software Professional",
    "Software & IT${AppStrings.split}UI/UX designer",
    "Software & IT${AppStrings.split}Web/Graphic Designer",
    "Other${AppStrings.split}Agent",
    "Other${AppStrings.split}Artist",
    "Other${AppStrings.split}Broker",
    "Other${AppStrings.split}Fitmess Professional",
    "Other${AppStrings.split}Interior Designer",
    "Other${AppStrings.split}Others",
    "Other${AppStrings.split}Politician",
    "Other${AppStrings.split}Security",
    "Other${AppStrings.split}Social Services/NGO Volunteer",
  ];

  List<String> annualIncomeList = [
    "No Income",
    "Rs. 0 - 1 Lakh",
    "Rs. 1 - 2 Lakh",
    "Rs. 2 - 3 Lakh",
    "Rs. 3 - 4 Lakh",
    "Rs. 4 - 5 Lakh",
    "Rs. 5 - 7 Lakh",
    "Rs. 7 - 10 Lakh",
    "Rs. 10 - 12 Lakh",
    "Rs. 12 - 15 Lakh",
    "Rs. 15 - 20 Lakh",
    "Rs. 20 - 35 Lakh",
    "Rs. 35 - 50 Lakh",
    "Rs. 50 - 75 Lakh",
    "Rs. 75 - 100 Lakh",
    "Rs. 1 Crore & Above",
  ];

  Map<String, String> annualIncomeInRupeesMap = {
    "No Income": "",
    "Rs. 0 - 1 Lakh": "Monthly income is ₹(0 to 8,3330 approx",
    "Rs. 1 - 2 Lakh": "Monthly income is ₹(8,333 to 16,667) approx",
    "Rs. 2 - 3 Lakh": "Monthly income is ₹(16,667 to 25,000) approx",
    "Rs. 3 - 4 Lakh": "Monthly income is ₹(25,000 to 33,333) approx",
    "Rs. 4 - 5 Lakh": "Monthly income is ₹(33,333 to 41,667) approx",
    "Rs. 5 - 7 Lakh": "Monthly income is ₹(41,667 to 58,333) approx",
    "Rs. 7 - 10 Lakh": "Monthly income is ₹(58,333 to 83,333) approx",
    "Rs. 10 - 12 Lakh": "Monthly income is ₹(83,333 to 100,000) approx",
    "Rs. 12 - 15 Lakh": "Monthly income is ₹(100,000 to 125,000) approx",
    "Rs. 15 - 20 Lakh": "Monthly income is ₹(125,000 to 166,667) approx",
    "Rs. 20 - 35 Lakh": "Monthly income is ₹(166,667 to 291,667) approx",
    "Rs. 35 - 50 Lakh": "Monthly income is ₹(291,667 to 416,667) approx",
    "Rs. 50 - 75 Lakh": "Monthly income is ₹(416,667 to 625,000) approx",
    "Rs. 75 - 100 Lakh": "Monthly income is ₹(625,000 to 833,333) approx",
    "Rs. 1 Crore & Above": "Monthly income is ₹8,33,333 approx",
  };

  final List<String> highestEducationList = [
    'Arts/Science${AppStrings.split}B.A.',
    'Arts/Science${AppStrings.split}B.Ed.',
    'Arts/Science${AppStrings.split}B.M.C. / B.M.M. / B.J.M.C.',
    'Arts/Science${AppStrings.split}B.Sc.',
    'Arts/Science${AppStrings.split}B.Sc. - Bachelor of Science',
    'Arts/Science${AppStrings.split}Bachelor of Fine Arts - BFA / BVA',
    'Arts/Science${AppStrings.split}Bachelor of Library Science',
    'Arts/Science${AppStrings.split}Bachelor of Physical Education',
    'Computers${AppStrings.split}B.C.A.',
    'Computers${AppStrings.split}B.IT',
    'Computers${AppStrings.split}M.C.A',
    'Computers${AppStrings.split}B.Tech',
    'Computers${AppStrings.split}M.Tech',
    'Doctorate${AppStrings.split}Doctor of Philosophy - Ph.D.',
    'Doctorate${AppStrings.split}M.Phil.',
    'Engineering/Design${AppStrings.split}B.Arch',
    'Engineering/Design${AppStrings.split}B.Des. / B.D.',
    'Engineering/Design${AppStrings.split}B.Pharm / B.Pharma.',
    'Engineering/Design${AppStrings.split}M.Pharma',
    'Finance/Commerce${AppStrings.split}B.Com.',
    'Finance/Commerce${AppStrings.split}CFA',
    'Finance/Commerce${AppStrings.split}Chartered Accountant - CA',
    'Finance/Commerce${AppStrings.split}CS',
    'Finance/Commerce${AppStrings.split}ICWA',
    'Finance/Commerce${AppStrings.split}M.Com.',
    'Islamic${AppStrings.split}Aalim Hafiz / Alaima Hafiza',
    'Law${AppStrings.split}Bachelor of Law - L.L.B.',
    'Law${AppStrings.split}L.L.M.',
    'Management${AppStrings.split}B.B.A.',
    'Management${AppStrings.split}BHM',
    'Management${AppStrings.split}M.B.A',
    'Medicine${AppStrings.split}B.A.M.S.',
    'Medicine${AppStrings.split}B.D.S.',
    'Medicine${AppStrings.split}B.H.M.S.',
    'Non-Graduate${AppStrings.split}Diploma',
    'Non-Graduate${AppStrings.split}High School',
    'Non-Graduate${AppStrings.split}Intermediate (12th)',
    'Non-Graduate${AppStrings.split}Trade School',
    'Others${AppStrings.split}Others',
  ];

  final Map<String, Map<String, List<String>>> countryMap = {
    "India": {
      'Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad'],
      'Karnataka': ['Bangalore', 'Mysore', 'Mangalore', 'Hubli', 'Belgaum'],
      'Tamil Nadu': [
        'Chennai',
        'Coimbatore',
        'Madurai',
        'Salem',
        'Tiruchirappalli'
      ],
      'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Varanasi', 'Agra', 'Noida'],
      'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar'],
      'West Bengal': [
        'Kolkata',
        'Darjeeling',
        'Siliguri',
        'Asansol',
        'Durgapur'
      ],
      'Rajasthan': ['Jaipur', 'Udaipur', 'Jodhpur', 'Ajmer', 'Bikaner'],
      'Kerala': [
        'Thiruvananthapuram',
        'Kochi',
        'Kozhikode',
        'Thrissur',
        'Alappuzha'
      ],
      'Punjab': ['Amritsar', 'Ludhiana', 'Jalandhar', 'Patiala', 'Bathinda'],
      'Haryana': ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Rohtak'],
      'Madhya Pradesh': ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain'],
      'Bihar': ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga'],
      'Telangana': [
        'Hyderabad',
        'Warangal',
        'Nizamabad',
        'Karimnagar',
        'Khammam'
      ],
      'Andhra Pradesh': [
        'Visakhapatnam',
        'Vijayawada',
        'Guntur',
        'Nellore',
        'Tirupati'
      ],
      'Odisha': ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Puri', 'Sambalpur'],
      'Assam': ['Guwahati', 'Dibrugarh', 'Silchar', 'Jorhat', 'Tezpur'],
      'Jharkhand': ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Hazaribagh'],
      'Chhattisgarh': ['Raipur', 'Bilaspur', 'Durg', 'Korba', 'Rajnandgaon'],
      'Goa': ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
      'Uttarakhand': [
        'Dehradun',
        'Haridwar',
        'Rishikesh',
        'Nainital',
        'Haldwani'
      ],
      'Himachal Pradesh': ['Shimla', 'Manali', 'Dharamshala', 'Kullu', 'Solan'],
      'Jammu & Kashmir': ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Leh'],
      'Meghalaya': ['Shillong', 'Tura', 'Nongstoin', 'Jowai', 'Baghmara'],
      'Tripura': [
        'Agartala',
        'Udaipur',
        'Dharmanagar',
        'Kailashahar',
        'Belonia'
      ],
      'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha'],
      'Manipur': ['Imphal', 'Thoubal', 'Bishnupur', 'Ukhrul', 'Churachandpur'],
      'Mizoram': ['Aizawl', 'Lunglei', 'Serchhip', 'Champhai', 'Kolasib'],
      'Arunachal Pradesh': ['Itanagar', 'Pasighat', 'Ziro', 'Tezu', 'Bomdila'],
      'Sikkim': ['Gangtok', 'Gyalshing', 'Namchi', 'Mangan', 'Rangpo'],
    },
    "Afghanistan": {
      'Kabul': ['Kabul City', 'Bagrami', 'Deh Sabz', 'Khaki Jabbar'],
      'Herat': ['Herat City', 'Gulran', 'Kushk', 'Shindand'],
      'Kandahar': ['Kandahar City', 'Spin Boldak', 'Zhari', 'Panjwai'],
      'Balkh': ['Mazar-i-Sharif', 'Balkh City', 'Sholgara', 'Dihdadi'],
      'Nangarhar': ['Jalalabad', 'Achin', 'Bati Kot', 'Surkh Rod'],
      'Helmand': ['Lashkargah', 'Garmsir', 'Musa Qala', 'Sangin'],
      'Ghazni': ['Ghazni City', 'Andar', 'Giro', 'Nawa'],
      'Badakhshan': ['Fayzabad', 'Jurm', 'Kishim', 'Wurduj'],
      'Paktia': ['Gardez', 'Zadran', 'Zurmat', 'Jaji'],
      'Parwan': ['Charikar', 'Jabal Saraj', 'Sayed Khel', 'Bagram'],
    },
    "Albania": {
      "Berat": ["Berat", "Kuçovë", "Poliçan"],
      "Dibër": ["Peshkopi", "Bulqizë", "Burrel"],
      "Durrës": ["Durrës", "Shijak", "Manëz"],
      "Elbasan": ["Elbasan", "Cërrik", "Peqin"],
      "Fier": ["Fier", "Patos", "Roskovec"],
      "Gjirokastër": ["Gjirokastër", "Tepelenë", "Memaliaj"],
      "Korçë": ["Korçë", "Pogradec", "Maliq"],
      "Kukës": ["Kukës", "Tropojë", "Has"],
      "Lezhë": ["Lezhë", "Laç", "Rrëshen"],
      "Shkodër": ["Shkodër", "Vau i Dejës", "Koplik"],
      "Tiranë": ["Tiranë", "Kamëz", "Vorë"],
      "Vlorë": ["Vlorë", "Sarandë", "Himarë"],
    },
    "Algeria": {
      "Algiers": [
        "Algiers",
        "Bab El Oued",
        "Kouba",
        "Birkhadem",
        "Bir Mourad Rais"
      ],
      "Oran": ["Oran", "Es Senia", "Bir El Djir", "Gdyel", "Arzew"],
      "Constantine": [
        "Constantine",
        "El Khroub",
        "Hamma Bouziane",
        "Ain Smara",
        "Didouche Mourad"
      ],
      "Blida": ["Blida", "Boufarik", "Mouzaia", "Ouled Yaich", "Beni Mered"],
      "Tizi Ouzou": [
        "Tizi Ouzou",
        "Draa Ben Khedda",
        "Ouaguenoun",
        "Larbaa Nath Irathen",
        "Azazga"
      ],
      "Annaba": ["Annaba", "El Hadjar", "Ain Berda", "Berrahal", "Sidi Amar"],
      "Sétif": ["Sétif", "El Eulma", "Ain Arnat", "Guellal", "Ain Abessa"],
      "Bejaia": ["Bejaia", "Tichy", "Amizour", "Kherrata", "Sidi Aich"],
      "Batna": ["Batna", "Timgad", "Barika", "Ain Touta", "Merouana"],
      "Tlemcen": ["Tlemcen", "Maghnia", "Ghazaouet", "Sebdou", "Remchi"]
    },
    "American Samoa": {
      'Tutuila': ['Pago Pago', 'Fagatogo', 'Nu’uuli', 'Tafuna'],
      'Manu’a Islands': ['Ta’u', 'Ofu', 'Olosega'],
      'Swains Island': ['Taulaga'],
    },
    'Australia': {
      'New South Wales': ['Sydney', 'Newcastle', 'Wollongong'],
      'Victoria': ['Melbourne', 'Geelong', 'Ballarat'],
      'Queensland': ['Brisbane', 'Gold Coast', 'Cairns'],
    },
    'Brazil': {
      'São Paulo': ['São Paulo', 'Campinas', 'Santos'],
      'Rio de Janeiro': ['Rio de Janeiro', 'Niterói', 'Petrópolis'],
      'Minas Gerais': ['Belo Horizonte', 'Uberlândia', 'Juiz de Fora'],
    },
    'Canada': {
      'Ontario': ['Toronto', 'Ottawa', 'Hamilton'],
      'Quebec': ['Montreal', 'Quebec City', 'Laval'],
      'British Columbia': ['Vancouver', 'Victoria', 'Kelowna'],
    },
    'China': {
      'Beijing': ['Beijing'],
      'Shanghai': ['Shanghai'],
      'Guangdong': ['Guangzhou', 'Shenzhen', 'Dongguan'],
    },
    'Hong Kong S.A.R': {
      'Hong Kong Island': ['Central', 'Wan Chai', 'Causeway Bay'],
      'Kowloon': ['Tsim Sha Tsui', 'Mong Kok', 'Yau Ma Tei'],
      'New Territories': ['Sha Tin', 'Tsuen Wan', 'Tuen Mun'],
    },
    'Iceland': {
      'Capital Region': ['Reykjavik', 'Kopavogur', 'Hafnarfjordur'],
      'Southern Peninsula': ['Keflavik', 'Grindavik', 'Sandgerdi'],
      'Westfjords': ['Ísafjörður', 'Bolungarvik', 'Patreksfjordur'],
    },
  };
}
